/**
 * Pre-built ID Card Background Library
 * These are designer-made background patterns using Fabric.js objects
 * Color placeholders (PRIMARY_COLOR, SECONDARY_COLOR) are replaced at runtime
 */

export interface IDCardBackground {
  id: string;
  name: string;
  category: 'gradient' | 'geometric' | 'minimal' | 'corporate' | 'creative';
  thumbnail: string;
  supportsPortrait: boolean;
  supportsLandscape: boolean;
  objects: object[];
}

// Canvas dimensions for reference
// Landscape: 324 x 204
// Portrait: 204 x 324

export const ID_CARD_BACKGROUNDS: IDCardBackground[] = [
  // ===== GRADIENT BACKGROUNDS =====
  {
    id: 'gradient-radial',
    name: 'Radial Glow',
    category: 'gradient',
    thumbnail: '🌅',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 162,
        top: 102,
        radius: 180,
        fill: 'PRIMARY_COLOR_LIGHT',
        opacity: 0.4,
        originX: 'center',
        originY: 'center',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 162,
        top: 102,
        radius: 120,
        fill: 'PRIMARY_COLOR',
        opacity: 0.3,
        originX: 'center',
        originY: 'center',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'gradient-diagonal',
    name: 'Diagonal Sweep',
    category: 'gradient',
    thumbnail: '🌈',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'polygon',
        points: [
          { x: 0, y: 204 },
          { x: 324, y: 80 },
          { x: 324, y: 204 },
        ],
        fill: 'SECONDARY_COLOR',
        opacity: 0.9,
        selectable: false,
        evented: false,
      },
      {
        type: 'polygon',
        points: [
          { x: 0, y: 204 },
          { x: 324, y: 120 },
          { x: 324, y: 204 },
        ],
        fill: 'SECONDARY_COLOR_DARK',
        opacity: 0.5,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'gradient-top-fade',
    name: 'Top Fade',
    category: 'gradient',
    thumbnail: '🌤️',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 60,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 60,
        width: 324,
        height: 30,
        fill: 'PRIMARY_COLOR_LIGHT',
        opacity: 0.5,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'gradient-corner',
    name: 'Corner Gradient',
    category: 'gradient',
    thumbnail: '🎨',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 0,
        top: 0,
        radius: 150,
        fill: 'PRIMARY_COLOR',
        opacity: 0.2,
        originX: 'center',
        originY: 'center',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 324,
        top: 204,
        radius: 120,
        fill: 'SECONDARY_COLOR',
        opacity: 0.2,
        originX: 'center',
        originY: 'center',
        selectable: false,
        evented: false,
      },
    ],
  },

  // ===== GEOMETRIC BACKGROUNDS =====
  {
    id: 'geometric-hexagon',
    name: 'Hexagon Pattern',
    category: 'geometric',
    thumbnail: '⬡',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      // Hexagon shapes scattered
      {
        type: 'polygon',
        points: [
          { x: 20, y: 0 }, { x: 40, y: 12 }, { x: 40, y: 34 },
          { x: 20, y: 46 }, { x: 0, y: 34 }, { x: 0, y: 12 },
        ],
        left: 280,
        top: 20,
        fill: 'PRIMARY_COLOR',
        opacity: 0.15,
        selectable: false,
        evented: false,
      },
      {
        type: 'polygon',
        points: [
          { x: 15, y: 0 }, { x: 30, y: 9 }, { x: 30, y: 26 },
          { x: 15, y: 35 }, { x: 0, y: 26 }, { x: 0, y: 9 },
        ],
        left: 300,
        top: 80,
        fill: 'SECONDARY_COLOR',
        opacity: 0.2,
        selectable: false,
        evented: false,
      },
      {
        type: 'polygon',
        points: [
          { x: 25, y: 0 }, { x: 50, y: 15 }, { x: 50, y: 43 },
          { x: 25, y: 58 }, { x: 0, y: 43 }, { x: 0, y: 15 },
        ],
        left: 260,
        top: 130,
        fill: 'PRIMARY_COLOR',
        opacity: 0.1,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'geometric-grid',
    name: 'Grid Lines',
    category: 'geometric',
    thumbnail: '▦',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FAFAFA',
        selectable: false,
        evented: false,
      },
      // Vertical lines
      { type: 'line', x1: 80, y1: 0, x2: 80, y2: 204, stroke: 'PRIMARY_COLOR', strokeWidth: 1, opacity: 0.1, selectable: false, evented: false },
      { type: 'line', x1: 160, y1: 0, x2: 160, y2: 204, stroke: 'PRIMARY_COLOR', strokeWidth: 1, opacity: 0.1, selectable: false, evented: false },
      { type: 'line', x1: 240, y1: 0, x2: 240, y2: 204, stroke: 'PRIMARY_COLOR', strokeWidth: 1, opacity: 0.1, selectable: false, evented: false },
      // Horizontal lines
      { type: 'line', x1: 0, y1: 50, x2: 324, y2: 50, stroke: 'PRIMARY_COLOR', strokeWidth: 1, opacity: 0.1, selectable: false, evented: false },
      { type: 'line', x1: 0, y1: 100, x2: 324, y2: 100, stroke: 'PRIMARY_COLOR', strokeWidth: 1, opacity: 0.1, selectable: false, evented: false },
      { type: 'line', x1: 0, y1: 150, x2: 324, y2: 150, stroke: 'PRIMARY_COLOR', strokeWidth: 1, opacity: 0.1, selectable: false, evented: false },
      // Accent rectangle
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 8,
        height: 204,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'geometric-diagonal-stripes',
    name: 'Diagonal Stripes',
    category: 'geometric',
    thumbnail: '╱',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      // Diagonal stripes at corner
      {
        type: 'line',
        x1: 280, y1: 0, x2: 324, y2: 44,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 3,
        opacity: 0.2,
        selectable: false,
        evented: false,
      },
      {
        type: 'line',
        x1: 295, y1: 0, x2: 324, y2: 29,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 3,
        opacity: 0.15,
        selectable: false,
        evented: false,
      },
      {
        type: 'line',
        x1: 310, y1: 0, x2: 324, y2: 14,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 3,
        opacity: 0.1,
        selectable: false,
        evented: false,
      },
      // Bottom accent
      {
        type: 'rect',
        left: 0,
        top: 194,
        width: 324,
        height: 10,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },

  // ===== MINIMAL BACKGROUNDS =====
  {
    id: 'minimal-accent-line',
    name: 'Single Accent',
    category: 'minimal',
    thumbnail: '─',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 6,
        height: 204,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'minimal-corner-dot',
    name: 'Corner Accent',
    category: 'minimal',
    thumbnail: '◉',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 10,
        top: 10,
        radius: 6,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'line',
        x1: 10, y1: 28, x2: 10, y2: 60,
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 2,
        opacity: 0.5,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'minimal-border',
    name: 'Subtle Border',
    category: 'minimal',
    thumbnail: '▢',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 8,
        top: 8,
        width: 308,
        height: 188,
        fill: 'transparent',
        stroke: 'PRIMARY_COLOR',
        strokeWidth: 1,
        opacity: 0.3,
        selectable: false,
        evented: false,
      },
    ],
  },

  // ===== CORPORATE BACKGROUNDS =====
  {
    id: 'corporate-header-band',
    name: 'Header Band',
    category: 'corporate',
    thumbnail: '▬',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 50,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 50,
        width: 324,
        height: 4,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'corporate-dual-tone',
    name: 'Dual Tone',
    category: 'corporate',
    thumbnail: '◧',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#F8F9FA',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 110,
        height: 204,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 110,
        top: 0,
        width: 4,
        height: 204,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'corporate-frame',
    name: 'Structured Frame',
    category: 'corporate',
    thumbnail: '▣',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      // Top bar
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 8,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      // Bottom bar
      {
        type: 'rect',
        left: 0,
        top: 196,
        width: 324,
        height: 8,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      // Left accent
      {
        type: 'rect',
        left: 0,
        top: 8,
        width: 4,
        height: 188,
        fill: 'SECONDARY_COLOR',
        selectable: false,
        evented: false,
      },
    ],
  },

  // ===== CREATIVE BACKGROUNDS =====
  {
    id: 'creative-splash',
    name: 'Color Splash',
    category: 'creative',
    thumbnail: '💫',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      // Large splash circles
      {
        type: 'circle',
        left: -40,
        top: -30,
        radius: 100,
        fill: 'PRIMARY_COLOR',
        opacity: 0.15,
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 280,
        top: 150,
        radius: 80,
        fill: 'SECONDARY_COLOR',
        opacity: 0.2,
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 200,
        top: -50,
        radius: 60,
        fill: 'PRIMARY_COLOR_LIGHT',
        opacity: 0.1,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'creative-abstract',
    name: 'Abstract Shapes',
    category: 'creative',
    thumbnail: '🎭',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: 'PRIMARY_COLOR',
        selectable: false,
        evented: false,
      },
      // Abstract white shapes
      {
        type: 'circle',
        left: 270,
        top: -20,
        radius: 80,
        fill: '#FFFFFF',
        opacity: 0.1,
        selectable: false,
        evented: false,
      },
      {
        type: 'rect',
        left: 240,
        top: 100,
        width: 100,
        height: 150,
        fill: '#FFFFFF',
        opacity: 0.05,
        angle: 45,
        selectable: false,
        evented: false,
      },
      {
        type: 'circle',
        left: 300,
        top: 180,
        radius: 40,
        fill: 'SECONDARY_COLOR',
        opacity: 0.3,
        selectable: false,
        evented: false,
      },
    ],
  },
  {
    id: 'creative-confetti',
    name: 'Confetti',
    category: 'creative',
    thumbnail: '🎊',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      // Small decorative rectangles (confetti)
      { type: 'rect', left: 20, top: 15, width: 8, height: 8, fill: 'PRIMARY_COLOR', opacity: 0.6, angle: 15, selectable: false, evented: false },
      { type: 'rect', left: 60, top: 30, width: 6, height: 6, fill: 'SECONDARY_COLOR', opacity: 0.5, angle: -20, selectable: false, evented: false },
      { type: 'rect', left: 290, top: 25, width: 10, height: 10, fill: 'PRIMARY_COLOR', opacity: 0.4, angle: 45, selectable: false, evented: false },
      { type: 'rect', left: 280, top: 60, width: 6, height: 6, fill: 'SECONDARY_COLOR', opacity: 0.5, angle: 10, selectable: false, evented: false },
      { type: 'rect', left: 300, top: 170, width: 8, height: 8, fill: 'PRIMARY_COLOR', opacity: 0.3, angle: -30, selectable: false, evented: false },
      { type: 'rect', left: 40, top: 180, width: 7, height: 7, fill: 'SECONDARY_COLOR', opacity: 0.4, angle: 25, selectable: false, evented: false },
      { type: 'circle', left: 100, top: 20, radius: 4, fill: 'PRIMARY_COLOR', opacity: 0.3, selectable: false, evented: false },
      { type: 'circle', left: 260, top: 140, radius: 5, fill: 'SECONDARY_COLOR', opacity: 0.4, selectable: false, evented: false },
    ],
  },
  {
    id: 'creative-wave',
    name: 'Wave Pattern',
    category: 'creative',
    thumbnail: '🌊',
    supportsPortrait: true,
    supportsLandscape: true,
    objects: [
      {
        type: 'rect',
        left: 0,
        top: 0,
        width: 324,
        height: 204,
        fill: '#FFFFFF',
        selectable: false,
        evented: false,
      },
      // Wave shapes using overlapping ellipses
      {
        type: 'ellipse',
        left: 0,
        top: 160,
        rx: 200,
        ry: 80,
        fill: 'PRIMARY_COLOR',
        opacity: 0.1,
        selectable: false,
        evented: false,
      },
      {
        type: 'ellipse',
        left: 150,
        top: 170,
        rx: 200,
        ry: 70,
        fill: 'SECONDARY_COLOR',
        opacity: 0.15,
        selectable: false,
        evented: false,
      },
      {
        type: 'ellipse',
        left: 80,
        top: 180,
        rx: 180,
        ry: 60,
        fill: 'PRIMARY_COLOR',
        opacity: 0.2,
        selectable: false,
        evented: false,
      },
    ],
  },
];

export function getBackgroundsByCategory(category?: string): IDCardBackground[] {
  if (!category) return ID_CARD_BACKGROUNDS;
  return ID_CARD_BACKGROUNDS.filter(bg => bg.category === category);
}

export function getBackgroundById(id: string): IDCardBackground | undefined {
  return ID_CARD_BACKGROUNDS.find(bg => bg.id === id);
}

export const BACKGROUND_CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'gradient', label: 'Gradient' },
  { id: 'geometric', label: 'Geometric' },
  { id: 'minimal', label: 'Minimal' },
  { id: 'corporate', label: 'Corporate' },
  { id: 'creative', label: 'Creative' },
] as const;
